export const HotelData = [
    {
      id: 1,
      image: require("../../assets/hotel_img.jpg"),
      hotelName: "Five Star Hotel",
      location: "Los Angeles",
      price: "100$/night",
    },
    {
      id: 2,
      image: require("../../assets/hotel_img.jpg"),
      hotelName: "Grand Hotel",
      location: "New York",
      price: "150$/night",
    },
    {
      id: 3,
      image: require("../../assets/hotel_img.jpg"),
      hotelName: "Home like hotel",
      location: "London",
      price: "200$/night",
    },
    {
      id: 4,
      image: require("../../assets/hotel_img.jpg"),
      hotelName: "Hilton",
      location: "Paris",
      price: "250$/night",
    },
    {
      id: 5,
      image: require("../../assets/hotel_img.jpg"),
      hotelName: "Radisson",
      location: "Berlin",
      price: "300$/night",
    },
    {
      id: 6,
      image: require("../../assets/hotel_img.jpg"),
      hotelName: "InterContinental",
      location: "Madrid",
      price: "350$/night",
    },
    {
      id: 7,
      image: require("../../assets/hotel_img.jpg"),
      hotelName: "Four Seasons",
      location: "Rome",
      price: "400$/night",
    },
    {
      id: 8,
      image: require("../../assets/hotel_img.jpg"),
      hotelName: "Hyatt",
      location: "Dubai",
      price: "450$/night",
    },
    {
      id: 9,
      image: require("../../assets/hotel_img.jpg"),
      hotelName: "MGM Grand",
      location: "Las Vegas",
      price: "500$/night",
    },
    {
      id: 10,
      image: require("../../assets/hotel_img.jpg"),
      hotelName: "Westin",
      location: "Seattle",
      price: "550$/night",
    },
    {
      id: 11,
      image: require("../../assets/hotel_img.jpg"),
      hotelName: "Ritz Carlton",
      location: "San Francisco",
      price: "600$/night",
    },
    {
      id: 12,
      image: require("../../assets/hotel_img.jpg"),
      hotelName: "The Palazzo",
      location: "Venice",
      price: "650$/night",
    },
    {
      id: 13,
      image: require("../../assets/hotel_img.jpg"),
      hotelName: "W Hotels",
      location: "Miami",
      price: "700$/night",
    },
    {
      id: 14,
      image: require("../../assets/hotel_img.jpg"),
      hotelName: "Hyatt",
      location: "Miami",
      price: "250$/night",
    },
    {
      id: 15,
      image: require("../../assets/hotel_img.jpg"),
      hotelName: "Marriot",
      location: "Miami",
      price: "400$/night",
    },
    {
      id: 16,
      image: require("../../assets/hotel_img.jpg"),
      hotelName: "Hotel one",
      location: "Miami",
      price: "300$/night",
    },
    {
      id: 17,
      image: require("../../assets/hotel_img.jpg"),
      hotelName: "serena",
      location: "New york",
      price: "500$/night",
    },
    {
      id: 18,
      image: require("../../assets/hotel_img.jpg"),
      hotelName: "Miami",
      location: "New york",
      price: "130$/night",
    },
    {
      id: 19,
      image: require("../../assets/hotel_img.jpg"),
      hotelName: "W Hotels",
      location: "Miami",
      price: "300$/night",
    },
    {
      id: 20,
      image: require("../../assets/hotel_img.jpg"),
      hotelName: "Grand hotel",
      location: "Washington",
      price: "240$/night",
    },
    {
      id: 21,
      image: require("../../assets/hotel_img.jpg"),
      hotelName: "Tourist hotel",
      location: "Verginia",
      price: "70$/night",
    },
    {
      id: 22,
      image: require("../../assets/hotel_img.jpg"),
      hotelName: "New hotel",
      location: "Dubai",
      price: "700$/night",
    },
    {
      id: 23,
      image: require("../../assets/hotel_img.jpg"),
      hotelName: "American hotel",
      location: "Miami",
      price: "70$/night",
    },
    {
      id: 24,
      image: require("../../assets/hotel_img.jpg"),
      hotelName: "W Hotels",
      location: "Los Angeles",
      price: "90$/night",
    },
    {
      id: 25,
      image: require("../../assets/hotel_img.jpg"),
      hotelName: "Own hotel",
      location: "New york",
      price: "120$/night",
    },
  ];
  