export const StoreData = [
    {
      id: 1,
      image: require("../../assets/hotel_img.jpg"),
      storeName: "Walgreens ",
      location: "Boca Raton, Florida",
      price: "100$/night",
    },
    {
      id: 2,
      image: require("../../assets/hotel_img.jpg"),
      storeName: "D watson",
      location: "Chesapeake, Virginia",
      price: "150$/night",
    },
    {
      id: 3,
      image: require("../../assets/hotel_img.jpg"),
      storeName: "Dollar General",
      location: "Austin, Texas",
      price: "200$/night",
    },
    {
      id: 4,
      image: require("../../assets/hotel_img.jpg"),
      storeName: "Hilton",
      location: "Dublin, California",
      price: "250$/night",
    },
    {
      id: 5,
      image: require("../../assets/hotel_img.jpg"),
      storeName: "Radisson",
      location: "Union, New Jersey",
      price: "300$/night",
    },
    {
      id: 6,
      image: require("../../assets/hotel_img.jpg"),
      storeName: "Walmart",
      location: "Plano, Texas",
      price: "350$/night",
    },
    {
      id: 7,
      image: require("../../assets/hotel_img.jpg"),
      storeName: "Target",
      location: "Seattle, Washington",
      price: "400$/night",
    },
    {
      id: 8,
      image: require("../../assets/hotel_img.jpg"),
      storeName: "Home Depot",
      location: "New York, New York",
      price: "450$/night",
    },
    {
      id: 9,
      image: require("../../assets/hotel_img.jpg"),
      storeName: "Lowe's ",
      location: "Las Vegas",
      price: "500$/night",
    },
    {
      id: 10,
      image: require("../../assets/hotel_img.jpg"),
      storeName: "Best Buy",
      location: "Seattle",
      price: "550$/night",
    },
    {
      id: 11,
      image: require("../../assets/hotel_img.jpg"),
      storeName: "Apple Store",
      location: "San Francisco",
      price: "600$/night",
    },
    {
      id: 12,
      image: require("../../assets/hotel_img.jpg"),
      storeName: "Macy's ",
      location: "Venice",
      price: "650$/night",
    },
    {
      id: 13,
      image: require("../../assets/hotel_img.jpg"),
      storeName: "Sears  ",
      location: "Miami",
      price: "700$/night",
    },
    {
      id: 14,
      image: require("../../assets/hotel_img.jpg"),
      storeName: "Nordstrom",
      location: "Miami",
      price: "250$/night",
    },
    {
      id: 15,
      image: require("../../assets/hotel_img.jpg"),
      storeName: "Sears ",
      location: "Miami",
      price: "400$/night",
    },
    {
      id: 16,
      image: require("../../assets/hotel_img.jpg"),
      storeName: "J.C. Penney",
      location: "Miami",
      price: "300$/night",
    },
    {
      id: 17,
      image: require("../../assets/hotel_img.jpg"),
      storeName: "Kohl's ",
      location: "New york",
      price: "500$/night",
    },
    {
      id: 18,
      image: require("../../assets/hotel_img.jpg"),
      storeName: "Bed Bath & Beyond ",
      location: "New york",
      price: "130$/night",
    },
    {
      id: 19,
      image: require("../../assets/hotel_img.jpg"),
      storeName: "T.J. Maxx",
      location: "Miami",
      price: "300$/night",
    },
    {
      id: 20,
      image: require("../../assets/hotel_img.jpg"),
      storeName: "Ross Stores",
      location: "Washington",
      price: "240$/night",
    },
    {
      id: 21,
      image: require("../../assets/hotel_img.jpg"),
      storeName: "Whole Foods Market",
      location: "Verginia",
      price: "70$/night",
    },
    {
      id: 22,
      image: require("../../assets/hotel_img.jpg"),
      storeName: "Dollar Tree",
      location: "Dubai",
      price: "700$/night",
    },
    {
      id: 23,
      image: require("../../assets/hotel_img.jpg"),
      storeName: "Dollar General ",
      location: "Miami",
      price: "70$/night",
    },
    {
      id: 24,
      image: require("../../assets/hotel_img.jpg"),
      storeName: "Five Below",
      location: "Los Angeles",
      price: "90$/night",
    },
    {
      id: 25,
      image: require("../../assets/hotel_img.jpg"),
      storeName: "CVS Pharmacy ",
      location: "New york",
      price: "120$/night",
    },
  ];
  