export const TouristData = [
    {
      id: 1,
      image: require("../../assets/hotel_img.jpg"),
      spotName: "Central Park ",
      location: " New York",
      price: "100$/night",
    },
    {
      id: 2,
      image: require("../../assets/hotel_img.jpg"),
      spotName: "Grand Canyon",
      location: "Arizona",
      price: "150$/night",
    },
    {
      id: 3,
      image: require("../../assets/hotel_img.jpg"),
      spotName: "Niagara Falls",
      location: "New York/Ontario",
      price: "200$/night",
    },
    {
      id: 4,
      image: require("../../assets/hotel_img.jpg"),
      spotName: "Las Vegas Strip ",
      location: "Las Vegas, Nevada",
      price: "250$/night",
    },
    {
      id: 5,
      image: require("../../assets/hotel_img.jpg"),
      spotName: "Disney World",
      location: " Orlando, Florida",
      price: "300$/night",
    },
    {
      id: 6,
      image: require("../../assets/hotel_img.jpg"),
      spotName: "The White House",
      location: "Washington D.C.",
      price: "350$/night",
    },
    {
      id: 7,
      image: require("../../assets/hotel_img.jpg"),
      spotName: "Times Square ",
      location: "New York City, New York",
      price: "400$/night",
    },
    {
      id: 8,
      image: require("../../assets/hotel_img.jpg"),
      spotName: "Statue of Liberty",
      location: "New York, New York",
      price: "450$/night",
    },
    {
      id: 9,
      image: require("../../assets/hotel_img.jpg"),
      spotName: "Universal Studios",
      location: "Los Angeles, California",
      price: "500$/night",
    },
    {
      id: 10,
      image: require("../../assets/hotel_img.jpg"),
      spotName: "Hollywood Walk",
      location: "Seattle",
      price: "550$/night",
    },
    {
      id: 11,
      image: require("../../assets/hotel_img.jpg"),
      spotName: "Golden Gate Bridge",
      location: "San Francisco",
      price: "600$/night",
    },
    {
      id: 12,
      image: require("../../assets/hotel_img.jpg"),
      spotName: "The Alamo",
      location: "Venice",
      price: "650$/night",
    },
    {
      id: 13,
      image: require("../../assets/hotel_img.jpg"),
      spotName: "Sears  ",
      location: "Miami",
      price: "700$/night",
    },
    {
      id: 14,
      image: require("../../assets/hotel_img.jpg"),
      spotName: "National Park",
      location: "Miami",
      price: "250$/night",
    },
    {
      id: 15,
      image: require("../../assets/hotel_img.jpg"),
      spotName: "Kennedy Space Center ",
      location: "Miami",
      price: "400$/night",
    },
    {
      id: 16,
      image: require("../../assets/hotel_img.jpg"),
      spotName: "Bourbon Street",
      location: "Miami",
      price: "300$/night",
    },
    {
      id: 17,
      image: require("../../assets/hotel_img.jpg"),
      spotName: "The French Quarter ",
      location: "New york",
      price: "500$/night",
    },
    {
      id: 18,
      image: require("../../assets/hotel_img.jpg"),
      spotName: "The National Mall  ",
      location: "New york",
      price: "130$/night",
    },
    {
      id: 19,
      image: require("../../assets/hotel_img.jpg"),
      spotName: "The Empire State Building",
      location: "Miami",
      price: "300$/night",
    },
    {
      id: 20,
      image: require("../../assets/hotel_img.jpg"),
      spotName: "The Roll Hall of Fame ",
      location: "Washington",
      price: "240$/night",
    },
    {
      id: 21,
      image: require("../../assets/hotel_img.jpg"),
      spotName: "The Field Museum",
      location: "Verginia",
      price: "70$/night",
    },
    {
      id: 22,
      image: require("../../assets/hotel_img.jpg"),
      spotName: "The Space Needle ",
      location: "Dubai",
      price: "700$/night",
    },
    {
      id: 23,
      image: require("../../assets/hotel_img.jpg"),
      spotName: "The Rock Hall ",
      location: "Miami",
      price: "70$/night",
    },
    {
      id: 24,
      image: require("../../assets/hotel_img.jpg"),
      spotName: "Yellowstone National Park",
      location: "Los Angeles",
      price: "90$/night",
    },
    {
      id: 25,
      image: require("../../assets/hotel_img.jpg"),
      spotName: "Yosemite National Park",
      location: "New york",
      price: "120$/night",
    },
  ];
  